# Generated by Django 5.0 on 2024-03-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_email', models.CharField(max_length=50)),
                ('Student_name', models.CharField(max_length=50)),
                ('student_password', models.CharField(max_length=100)),
                ('teacher_email', models.CharField(max_length=50)),
                ('teacher_password', models.CharField(max_length=100)),
                ('Year', models.CharField(max_length=10)),
                ('Fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
