# Generated by Django 5.0 on 2024-03-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_members',
            name='Student_name',
        ),
    ]
