# Generated by Django 5.0 on 2024-03-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_student_teacher_delete_user_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='New_Student', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
