# Generated by Django 5.0 on 2024-03-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('patterns', models.JSONField()),
                ('responses', models.JSONField()),
            ],
        ),
    ]
