# Generated by Django 5.0 on 2024-03-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fee',
            field=models.CharField(default='0.00', max_length=15),
        ),
    ]
