# Generated by Django 5.0 on 2024-03-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_alter_student_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='field_of_study',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='joining_year',
            field=models.CharField(default='', max_length=100),
        ),
    ]
